#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';

my @arr = qw/ ccc bbb aaa ddd /;
say "\n======Before sort======\n";
while (my ($index, $value) = each @arr) {
  say "$index: $value";
}

@arr = sort @arr;
say "\n======After sort======\n";
while (my ($index, $value) = each @arr) {        #same as foreach $index (0 .. $#arr)
  say "$index: $value";
}

say "\n======Test Hash and Each======\n";

my %hash_test = ("pig"=>111, "cat"=>999, "sss"=>6546);

while (my ($index, $value) = each %hash_test) {
  say "$index: $value";
}
